### ISSUE TITLE
前端开源

### ISSUE THREAD

**Issue by bootskill** [ixrjog/opscloud-web-dist#2]
请问前端开源吗

**Comment by ixrjog** [comment]
热度不够暂不开源

**Comment by sailingchen** [comment]
要多点完善推广下，如果不是亲自去安装实践，不会知道这个系统真正能干啥

**Comment by ixrjog** [comment]
oc服务端代码即文档全接口api，不用前端也可以2次开发，群里有问题我会及时回答

**Comment by sailingchen** [comment]
好像没有看到哪里有群，我想不自力量二次开发学习下，虽然我还没写过几行Java代码哈

**Comment by ixrjog** [comment]
q群:630913972

**Comment by caliahub** [comment]
想亲手实践并二次开发，恳请开源前端

**Comment by ixrjog** [comment]
我不能让竞争公司达到我司运维水准

**Comment by sailingchen** [comment]
@caliahub  vue.js 是比较好写的，组件非常多，拿来用就是了，后端都开源了，重写一个界面也不难。

**Comment by inmapx** [comment]
恳请开源前端

**Comment by jsjinfuming** [comment]
前端开源，麻烦告诉下

**Comment by stjava** [comment]
恳请开源前端

**Comment by ixrjog** [comment]
4月底开源

**Comment by 370569218** [comment]
您好，现在前端开源了吗

**Comment by ixrjog** [comment]
https://github.com/ixrjog/opscloud-web
